export const FETCH_CUSTOMER_INITIAL = "FETCH_CUSTOMER_INITIAL";
export const FETCH_CUSTOMER_SUCCESS = "FETCH_CUSTOMER_SUCCESS";
export const FETCH_CUSTOMER_FAILURE = "FETCH_CUSTOMER_FAILURE";

export const UPDATE_CUSTOMER_INITIAL = "UPDATE_CUSTOMER_INITIAL";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILURE = "UPDATE_CUSTOMER_FAILURE";

export const ADD_CUSTOMER_INITIAL = "ADD_CUSTOMER_INITIAL";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILURE = "ADD_CUSTOMER_FAILURE";

export const FETCH_CUSTOMERS_INITIAL = "FETCH_CUSTOMERS_INITIAL"


export const CHANGE_INPUT = "CHANGE_INPUT";
export const CUSTOMER_INPUT_ERROR = "CUSTOMER_INPUT_ERROR";
export const ON_CUSTOMER_INPUT_CHANGE_MODE_TOGGLE = "ON_CUSTOMER_INPUT_CHANGE_MODE_TOGGLE"
